# Generated by Django 2.1.1 on 2018-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
