# Generated by Django 2.1.1 on 2018-10-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='language',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
