# Generated by Django 2.1.1 on 2018-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='location',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
