# Generated by Django 2.1.1 on 2018-10-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_liked',
        ),
    ]
