# Generated by Django 2.1.1 on 2018-10-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_song_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
    ]
