# Generated by Django 2.1.1 on 2018-10-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_favorite_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='album',
        ),
    ]
