# Generated by Django 2.1.1 on 2018-10-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_favorite_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_picture', models.CharField(max_length=1000)),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
    ]
