# Generated by Django 2.1.1 on 2018-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_userdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
