# Generated by Django 2.1.1 on 2018-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20181028_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_picture',
            field=models.CharField(max_length=1000),
        ),
    ]
