# Generated by Django 2.1.1 on 2018-10-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20181028_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='user',
            new_name='user_name',
        ),
    ]
