# Generated by Django 2.1.1 on 2018-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20181028_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albums_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
